### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by milost** [milost/RSSGrab#7]
During the execution a grabber #5, we are only interested in discovering new articles. Instead of saving articles multiple times (because they are mentioned in multiple subsequent feed grabbing sessions) we only want to identify what's new in a feed that we crawl multiple times.

Therefore, we need a way to memorize what was in the feed the last time we crawled it. Using this information we can easily calculate the difference between the two crawls and only grab the articles that are new.

One possibility is to use a simple caching service like a simple hashmap, [Beaker](http://beaker.readthedocs.org/en/latest/) or [Redis](http://redis.io/) to store all the URLs that were contained in the feed during the previous crawl.

This issue is directly connected to Issue #5

**Comment by pkuhn** [comment]
Can this be solved by storing the Id (which is equal to the link of the article) in the database and simply store the most recent one?

**Comment by milost** [comment]
This could be possible if the id is unique. Just give it a try ... if it doesn't work out, we'll think of something else.
